BEGIN;

CREATE TABLE usuarios (
  id BIGINT
    GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,

  nome VARCHAR(120)
    NOT NULL,

  email VARCHAR(160)
    NOT NULL,

  senha VARCHAR(255)
    NOT NULL,

  whatsapp VARCHAR(11)
    NOT NULL,

  ativo BOOLEAN
    NOT NULL
    DEFAULT TRUE,

  email_verificado_em TIMESTAMPTZ,

  ultimo_login_em TIMESTAMPTZ,

  senha_alterada_em TIMESTAMPTZ
    NOT NULL
    DEFAULT NOW(),

  created_at TIMESTAMPTZ
    NOT NULL
    DEFAULT NOW(),

  updated_at TIMESTAMPTZ
    NOT NULL
    DEFAULT NOW(),

  CONSTRAINT usuarios_nome_valido
    CHECK (
      CHAR_LENGTH(
        BTRIM(nome)
      ) BETWEEN 2 AND 120
    ),

  CONSTRAINT usuarios_email_normalizado
    CHECK (
      email =
        LOWER(
          BTRIM(email)
        )
    ),

  CONSTRAINT usuarios_email_formato_basico
    CHECK (
      POSITION(
        '@' IN email
      ) > 1
    ),

  CONSTRAINT usuarios_whatsapp_valido
    CHECK (
      whatsapp ~
        '^[0-9]{10,11}$'
    ),

  CONSTRAINT usuarios_senha_nao_vazia
    CHECK (
      CHAR_LENGTH(
        senha
      ) > 0
    )
);

/*
 * Impede duplicidade ignorando
 * letras maiúsculas e minúsculas.
 */
CREATE UNIQUE INDEX
  usuarios_email_unique
ON usuarios (
  LOWER(email)
);

/*
 * Facilita consultas de contas ativas.
 */
CREATE INDEX
  usuarios_ativos_idx
ON usuarios (
  id
)
WHERE ativo = TRUE;

/*
 * Função reutilizável nas próximas tabelas.
 * Atualiza updated_at automaticamente.
 */
CREATE OR REPLACE FUNCTION
  atualizar_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();

  RETURN NEW;
END;
$$;

CREATE TRIGGER
  usuarios_atualizar_updated_at
BEFORE UPDATE
ON usuarios
FOR EACH ROW
EXECUTE FUNCTION
  atualizar_updated_at();

COMMIT;