BEGIN;

ALTER TABLE whatsapp_mensagens
  DROP CONSTRAINT IF EXISTS
    whatsapp_mensagens_tipo_check;

ALTER TABLE whatsapp_mensagens
  ADD CONSTRAINT whatsapp_mensagens_tipo_check
  CHECK (
    tipo IN (
      'NOVO_AGENDAMENTO_PROFISSIONAL',
      'CONFIRMACAO_AGENDAMENTO_CLIENTE',
      'LEMBRETE_AGENDAMENTO_CLIENTE',
      'LEMBRETE_AGENDAMENTO_PROFISSIONAL',
      'CANCELAMENTO_AGENDAMENTO_PROFISSIONAL',
      'CANCELAMENTO_AGENDAMENTO_CLIENTE'
    )
  );

COMMIT;
