BEGIN;

CREATE TABLE redefinicoes_senha (
  id BIGINT
    GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,

  usuario_id BIGINT
    NOT NULL
    REFERENCES usuarios(id)
    ON DELETE CASCADE,

  token_hash CHAR(64)
    NOT NULL
    UNIQUE,

  expira_em TIMESTAMPTZ
    NOT NULL,

  usado_em TIMESTAMPTZ,

  created_at TIMESTAMPTZ
    NOT NULL
    DEFAULT NOW(),

  CONSTRAINT redefinicoes_senha_expiracao_valida
    CHECK (expira_em > created_at)
);

CREATE INDEX redefinicoes_senha_usuario_idx
ON redefinicoes_senha (
  usuario_id,
  created_at DESC
);

CREATE INDEX redefinicoes_senha_expiracao_idx
ON redefinicoes_senha (
  expira_em
)
WHERE usado_em IS NULL;

COMMIT;
